# Assignment

1. Create an array of shape (10, 10) with uint8 random values.
2. print the shape, size and dimension, 
3. Compute the sum of the third row to the last.
4. Compute the average of the columns

In [3]:
import numpy as np

# Question 01
np.random.seed(53)
q1 = np.random.randint(0,256, (10,10), dtype='uint8')

# Question 02
print('Shape=', q1.shape)
print('Size=', q1.size)
print('Dimension=', q1.ndim)
print('Type:', q1.dtype)

# Question 03
q3 = q1[3:]
print("\nThird rows to the last row:\n", q3)
sum_rows = np.sum(q3, axis=1)
total_sum = np.sum(q3)
print("\nSUM of each row from 3rd to 7th row:\n", sum_rows)
print("\nSUM of all the rows of 3rd to 7th row:\n", total_sum)

# Question 04
average_rows = np.mean(q3, axis=1)
mean_average = np.mean(q3)
print("\nMEAN of each row from 3rd to 7th row:\n", average_rows)
print("\nMEAN of all the rows of 3rd to 7th row:\n", mean_average)

Shape= (10, 10)
Size= 100
Dimension= 2
Type: uint8

Third rows to the last row:
 [[ 58 198  63  91 250 149 127  87 103 185]
 [ 48 229  38 137  88  31 242 115 186  44]
 [212 211 140   4  25 125 137   9 185  67]
 [ 58 115  98 223 197  12 119 122  18 228]
 [ 83 188 122 112   8  89  89 180  73 153]
 [203  43 109  34 212  51 180 226  35 224]
 [141  66  38 181 100  75  90 201  49  12]]

SUM of each row from 3rd to 7th row:
 [1311 1158 1115 1190 1097 1317  953]

SUM of all the rows of 3rd to 7th row:
 8141

MEAN of each row from 3rd to 7th row:
 [131.1 115.8 111.5 119.  109.7 131.7  95.3]

MEAN of all the rows of 3rd to 7th row:
 116.3
